### ISSUE TITLE
open base url

### ISSUE THREAD

**Issue by deTian0** [thisisishara/llm-response-bot#2]
请问怎么修改 openai base url？

在  actions/api_llm/llms.py 中直接指定 open.base_url 无效
设置   OPENAI_BASE_URL 无效

**Comment by thisisishara** [comment]
抱歉，在此实现中，无法更改 OpenAI 基本 URL。

一种方法是在项目根目录的 .env 中添加 OPENAI_BASE_URL，然后在 Rasa 操作中使用它。

如果您使用 Docker，则可以使用以下命令直接加载它：
````
BASE_URL = os.environ.get("OPENAI_BASE_URL")
````

如果您在 Docker 外部运行此程序，则必须使用 python_dotenv 包在操作脚本内加载 .env 文件：
````
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.environ.get("OPENAI_BASE_URL")
````
